theme: minimal-mistakes-jekyll 
minimal_mistakes_skin: dark
google_analytics:
logo: /images/gh-logo.png
title: ""
enable_copy_code_button: true

atom_feed:
  hide: true

plugins:
  - jemoji
  - jekyll-octicons
